API_ID: 16596628
API_HASH: 421764a823ee2dff786d413aea09959f
BOT_TOKEN: 5791754081:AAG_8IU5F1GdJxtyG_KFH3LE1jEeIXDkG4Y


MONGO_URL: mongodb+srv://useor:5J9hvA53Ul1G4wNV@cluster0.3b1bnas.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13757.c273.us-east-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 13757
REDIS_PASS: hdD4WujQwT8ouE5BD7LVUFuanC0LyBBa

SESSION_API_ID: 15649932
SESSION_API_HASH: ac748828574bf5b0ff75eef790d902df
SESSION_STRING: 1BVtsOH8BuzDHaAbE0a3wrUkly6BePUlZs64bNFtYo0vFRX5QHjhsbeDeY9HnbmCeb7ew3Xs9wmyvksxuyDHoozb9etkXZYED_sqS8eKxXSYva-OzslGG91sXTmGjXRzNXArWpriEOuTtb5MhwaEvGbxT94e4Nvudi_2ikZ4qKwgGcvwK9VK0Ry9LXQUHe7Od2dECL7v4znKVLuICLW74Uz8WAItFTYqQ42D7FEZe5890YqxriTeKCy7I56spzjKtgI1l_zSHeoJL5Lr2eGo9FoRjskHm3QD-EyY-lzpXGPj5YygfX27PNCAamCz12p4Loy_v5AUWXFkZ_OB0nOP2Z-u41aAKWGE=

ADMINS: 
  - 5383908433
  - 5136746907
  - 5681019071

OWNER: 5136746907
OWNER: 5681019071

BOT_PIC: https://telegra.ph/file/3c648222a5d08d8dcac11.png
OWNER_PIC: https://telegra.ph/file/3c648222a5d08d8dcac11.png


SUPPORT_CHAT: xteambdchat
# LOG_CHAT: -1001657108198
LOG_CHAT: -1001786848035



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

