API_ID: 15649932
API_HASH: ac748828574bf5b0ff75eef790d902df
BOT_TOKEN: 5791754081:AAGqw45HHKBWCpkJaM-LithfZmOQIIXhrSo


MONGO_URL: mongodb+srv://prouser:WDY9orTd99wiWNZ1@cluster0.nwrik.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13011.c21073.us-east-1-mz.ec2.cloud.rlrcp.com
REDIS_PORT: 13011
REDIS_PASS: QI8BYzAni3OeTPAk4MLQcMQ7BrLWW17V

SESSION_API_ID: 11197200
SESSION_API_HASH: e569a3f232f49667be19490e6f69b8c9
SESSION_STRING: 1BVtsOKwBu5ZaSAo6-370kzmuIOTzHE-jqptNr0QsrAAOAtzQW8F0OcZYlFCelveLQYIGeIZ-RwkB4F_BhusrRw5dKajH5QefY0TsT_7l6SedQvIwiJ59Mso1SifXZ1_Y2kK63s_suY008E1Ns3JPbNUd-zLDMHNeMdExLbyFcJZFW5fDBcl5GLIuBt9Gj267w0UiAnp7-dc4ebxbT1gJAtQGKZ39dyBEzbO0CB4mkQZlCVoO0TZwhgffC3ZCH_KnWzoFO_tmwokb8GXwJxsOEluckzW3Owu2dpVZqxtIAlCkv3Z_CxsJZefGOxkZYrRmsLW7B6Nxht59NkqdqvTsJqnRSdmLrUI=

ADMINS: 
  - 5383908433
  - 5136746907
  - 5383908433

OWNER: 5136746907
OWNER: 5383908433

BOT_PIC: https://telegra.ph/file/3c648222a5d08d8dcac11.png
OWNER_PIC: https://telegra.ph/file/3c648222a5d08d8dcac11.png


SUPPORT_CHAT: xteambdchat
# LOG_CHAT: -1001657108198
LOG_CHAT: -1001786848035



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

